---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: blog
  label: Changelog
  create: all
  match: "**/*"
- type: directory
  path: docs/troubleshooting
  label: Troubleshooting
  create: all
  match: "**/*"
- type: directory
  path: docs/platform
  label: Platform
  create: all
  match: "**/*"
- type: directory
  path: docs/ci
  label: CI
  create: all
  match: "**/*"
- type: directory
  path: docs/embedded
  label: Embedded
  create: all
  match: "**/*"
- type: directory
  path: docs/android
  label: Android
  create: all
  match: "**/*"
upload_dir: static/img
public_path: "/binary-assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn start --port 80
